//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehberiOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKISILER
    {
        public int KISIID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string MESLEK { get; set; }
        public string ADRES { get; set; }
        public string CINSIYET { get; set; }
        public Nullable<System.DateTime> DOGUMGUNU { get; set; }
        public string TEL { get; set; }
        public string MAİL { get; set; }
    }
}
